title: Alumni SMPN 1 Pace
description: Rang-rangginang udah cukup.
author: Alumni SMPN 1 Pace Th. 2005
logo: https://rangginang.github.io/static/img/avatar.png
github: https://github.com/rangginang
about: Menghabiskan jajanan lebaran
disqus_shortname: rangginang
google_analytics: 
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-graduation-cap
    - text: Album
      url: /projects/
      icon: fa-desktop
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      
social:
    - icon: fa-facebook
      link: 'https://www.facebook.com/groups/SMP1PACE/'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "https://rangginang.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
